version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "9229:9229"
    command: ["bun", "--inspect", "backend/src/app.ts"]