name: miauflix

services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN               # Required
      - NET_RAW                 # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - TOKEN="${NORDVPN_TOKEN}"
      - CONNECT="${NORDVPN_SERVER}"
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.0.0/16  # So it can be accessed within the local network
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Recomended if using ipv4 only
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASS
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - TZ="${TZ}"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
    networks:
      - default
    restart: unless-stopped

#include:
  # Development docker compose, uncomment when you want to edit the code
#  - ./docker-compose.dev.yml

volumes:
  redis_data:
  postgres_data:
  jackett_config:
  jackett_downloads:
  seq_data:
