version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      - "6499:6499"
    command: ["bun", "--inspect", "--watch", "backend/src/app.ts"]
