version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=miauflix
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vilnius
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - jackett_config:/config
      - jackett_downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  jackett_config:
  jackett_downloads:
